# Generated by Django 4.1.7 on 2023-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Message',
            field=models.CharField(max_length=500),
        ),
    ]
