# Generated by Django 4.1.7 on 2023-03-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_contactus_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cropdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('season', models.CharField(max_length=100)),
            ],
        ),
    ]
